language: python
python:
    - "2.7"

sudo: false
cache: pip

install: "pip install sphinx~=1.5.3"
script: cd docs && make html && cd ..

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GH_REPO_TOKEN
    keep-history: true
    on:
        branch: master
    project-name: mayaMatchMoveSolver
    local-dir: "./docs/build/html"
